# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoDhcpDns < Formula
  desc "Make DNS go through DHCP"
  homepage "https://github.com/mazzz1y/go-dhcp-dns"
  version "1.0.0-1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mazzz1y/go-dhcp-dns/releases/download/v1.0.0-1/go-dhcp-dns_1.0.0-1_darwin_amd64.tar.gz"
      sha256 "07663f7dc0e08c317256f6cbf5423ab2585d25ec27f16423aa11031ec08a8639"

      def install
        bin.install "go-dhcp-dns"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mazzz1y/go-dhcp-dns/releases/download/v1.0.0-1/go-dhcp-dns_1.0.0-1_darwin_arm64.tar.gz"
      sha256 "e846c5ebc08e3187d16411929adbde7e54a6a95f7a23faa29a0a507f092b1909"

      def install
        bin.install "go-dhcp-dns"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mazzz1y/go-dhcp-dns/releases/download/v1.0.0-1/go-dhcp-dns_1.0.0-1_linux_amd64.tar.gz"
        sha256 "f692f7910fac5a4e775d129e313275f025120ede3b7fff9082d50b23d4f1ff0a"

        def install
          bin.install "go-dhcp-dns"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mazzz1y/go-dhcp-dns/releases/download/v1.0.0-1/go-dhcp-dns_1.0.0-1_linux_arm64.tar.gz"
        sha256 "627af785c2823c6cbba0b8aa00a7f34e85579455b81522d6c864fc82d0067047"

        def install
          bin.install "go-dhcp-dns"
        end
      end
    end
  end

  service do
    run [opt_bin/"go-dhcp-dns"]
    keep_alive true
    error_log_path "#{var}/log/go-dhcp-dns.err.log"
  end
end
