# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoDhcpDns < Formula
  desc "Make DNS go through DHCP"
  homepage "https://github.com/mazzz1y/go-dhcp-dns"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mazzz1y/go-dhcp-dns/releases/download/v1.0.1/go-dhcp-dns_1.0.1_darwin_amd64.tar.gz"
      sha256 "bcb789c8ecdeca3c86e2bd6bae12d2130a516d4e4d2293017fbc92173059cd9a"

      def install
        bin.install "go-dhcp-dns"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mazzz1y/go-dhcp-dns/releases/download/v1.0.1/go-dhcp-dns_1.0.1_darwin_arm64.tar.gz"
      sha256 "06ac5638e234e184250f383f6b54f67fe186c7dfc7eb723a7bbd38611c4aa3e2"

      def install
        bin.install "go-dhcp-dns"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mazzz1y/go-dhcp-dns/releases/download/v1.0.1/go-dhcp-dns_1.0.1_linux_amd64.tar.gz"
        sha256 "ba89691fd7a6f9de9dcac35b0277b24c9d6b5836a030ebc3c0176b0f8b6be483"

        def install
          bin.install "go-dhcp-dns"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mazzz1y/go-dhcp-dns/releases/download/v1.0.1/go-dhcp-dns_1.0.1_linux_arm64.tar.gz"
        sha256 "8c7bf18ab4de3ef3ae7c536c4d5de494b38aca7e7412d8cb55dbd43891c705ec"

        def install
          bin.install "go-dhcp-dns"
        end
      end
    end
  end

  service do
    run [opt_bin/"go-dhcp-dns"]
    keep_alive true
    error_log_path "#{var}/log/go-dhcp-dns.err.log"
  end
end
